### ISSUE TITLE
import Model

### ISSUE THREAD

**Issue by ghost** [reuben/ds-qttest#1]
Reuben, como faço para passar o modelo do deepspeech no código? devo salvar em alguma pasta específica ou na chamada do main.py? Abraços!
![Captura de Tela 2020-01-14 às 14 49 42](https://user-images.githubusercontent.com/52043395/72384743-d3b90d00-36fc-11ea-9df7-c027825ed484.jpg)

**Comment by reuben** [comment]
https://github.com/reuben/ds-qttest/blob/aa29514beb01c468abb9cfab0a2359e86755bd43/main.py#L142-L146

Mas o erro da screenshot (no futuro, copie e cole em vez de postar screenshots, que não são acessíveis e não permitem buscar pelo texto) não é relacionado a isso, é porque você está usando Anaconda. Use o virtualenv: https://docs.python.org/3/library/venv.html#creating-virtual-environments

**Comment by ghost** [comment]
Obrigada, Reuben! Eu segui suas instruções e mesmo usando virtualenv ocorreu o mesmo erro. Acredito que o deepspeech não seja compatível para macOS 10.11.6 como mencionado aqui https://discourse.mozilla.org/t/error-example-from-deepspeech-repo-readme/50057/10
